name: testing
on:
  push: 
    branches:
      - main
jobs:
  Rollback-Frontend:
    runs-on: self-hosted
    outputs:
      release-sha: ${{ steps.find-commit.outputs.release-sha }}
    steps:
      - name: Find Commit with Release SHA
        id: find-commit
        run: |
          RELEASE_SHA=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
            | jq -r '.artifacts[] | select(.name=="release-sha") | .workflow_run.head_sha')
          echo "release-sha=${RELEASE_SHA}" >> $GITHUB_OUTPUT        
  Output-Release-SHA:
    runs-on: self-hosted
    needs: Rollback-Frontend
    steps:
      - name: Output Release SHA
        run: |
          echo "${{ needs.Rollback-Frontend.outputs.release-sha }}"