name: testing
on:
  push: 
    branches:
      - main
jobs:
  Deploy-Frontend:
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Outputting github.sha
        run: |
          echo "${{ github.sha }}" > release_sha.txt
      - name: Upload Release SHA
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: release-sha
          path: release_sha.txt