name: Download Artifact from Tag

on:
  push:
    branches:
      - main

jobs:
  download-artifact:
    runs-on: self-hosted
    env:
      BUCKET_NAME: bucket-for-release-versions
    steps:
      - name: uploads to s3 bucket
        run: |
          echo "test" > test.txt
          aws s3 cp test.txt s3://${{ env.BUCKET_NAME }}/test.txt
