name: Download Artifact from Tag

on:
  push:
    branches:
      - main

jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Download release-sha.txt artifact
        uses: dawidd6/action-download-artifact@v9
        with:
          commit: ${{ github.sha }}   # the commit associated with the tag
          name: release-sha.txt       # artifact name to download
          path: ./downloaded         # destination directory
