name: Frontend Deployment on EC2
on:
  push:
    branches:
      - main

jobs:
  Deploy-Frontend:
    runs-on: self-hosted
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Runs Custom Script
        run: |
          chmod 700 frontend/change-pub-ip.sh
          ./frontend/change-pub-ip.sh

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Frontend Container
        run: |
          if [ $(docker ps -a -q) ]; then
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
          fi
          docker build -t r3dchilli/frontend-image:${{ github.sha }} frontend/
          docker run -d -p 80:80 r3dchilli/frontend-image:${{ github.sha }}
#docker push r3dchilli/frontend-image:${{ github.sha }}

      - name: Tag and Push Release
        if: success()
        run: |
          docker tag r3dchilli/frontend-image:${{ github.sha }} r3dchilli/frontend-image:release
          docker push r3dchilli/frontend-image:release

  Rollback-Frontend:
    runs-on: self-hosted
    needs: Deploy-Frontend
    if: failure()
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Previous Release Frontend Container
        run: |
          if [ $(docker ps -a -q) ]; then
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
          fi
          docker pull r3dchilli/frontend-image:release
          docker run -d -p 80:80 r3dchilli/frontend-image:release 