name: Frontend Deployment on EC2
on:
  push:
    branches:
      - main

jobs:
  Deploy-Frontend:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Runs Custom Script
        run: |
          chmod 700 frontend/change-pub-ip.sh
          ./frontend/change-pub-ip.sh

      - name: Run Frontend Container
        run: |
          if [ $(docker ps -a -q) ]; then
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
          fi
          docker build -t r3dchilli/frontend-image:${{ github.sha }} frontend/
          docker run -d -p 80:80 r3dchilli/frontend-image:${{ github.sha }}
          docker push r3dchilli/frontend-image:${{ github.sha }}
